{
 "title": "The Four Golden Signals(LETS)",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Latency",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_server_request_duration_seconds_bucket[5m])) by (le))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(http_server_request_duration_seconds_bucket[5m])) by (le))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(http_server_request_duration_seconds_bucket[5m])) by (le))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Process Cpu Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(process_cpu_time_seconds_total[5m])) by (instance) * 100 *100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Saturation",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 3, "x": 21, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(rate(process_cpu_time_seconds_total[5m])) by (instance) / 32) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "(sum(rate(http_server_request_duration_seconds_count{http_response_status_code=\"500\"}[5m]))/sum(rate(http_server_request_duration_seconds_count[5m]))) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Using",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "dotnet_process_memory_working_set_bytes/(1024*1024)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Saturation",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 3, "x": 21, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(dotnet_process_memory_working_set_bytes / 34359738368) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "The number of requests per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum(rate(http_server_request_duration_seconds_count[5m]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}