# Kubernetes API versiyonu ve kaynak tipi
apiVersion: v1
kind: Secret
metadata:
  # Secret için benzersiz bir isim
  name: rabbitmq-connection-secret
# Secret tipi. 'Opaque' genel amaçlı, key-value (anahtar-değer) verileri için kullanılır.
type: Opaque
# 'stringData' alanı, değerleri şifrelemeden (Base64) düz metin olarak yazmanızı sağlar.
stringData:
  # .NET Core configuration sisteminin "ConnectionStrings:RabbitMq" olarak algılayacağı anahtar.
  # Ortam değişkenlerinde iki alt çizgi (__), JSON'daki iki nokta üst üste (:) karakterine denk gelir.
  ConnectionStrings__RabbitMq: "amqp://user:Vxsp7zRTobjaCKR0@my-rabbitmq.default.svc.cluster.local:5672"