apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: rabbitmq-worker-scaler
  namespace: default
spec:

  scaleTargetRef:
    name: image-process-workerservice-deployment
  
  pollingInterval: 15
  

  cooldownPeriod: 100 
  r!
  minReplicaCount: 1
  
  maxReplicaCount: 10
      
  triggers:
    - type: rabbitmq
      metadata:
  
        queueName: "ResizeImageCommand"
        

        queueLength: "5"
        includeUnacked: "true"
      authenticationRef:
        name: keda-rabbitmq-auth